version: "2"

services:
################ LAMP Stack.
# Requires mariadb container.        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - '82:80'
    networks:
      internal:
      shared:
        ipv4_address: 172.55.0.9
        
  adminer:
    image: adminer
    links:
      - mariadb
      - postgres
      - mongo
    depends_on:
      - mariadb
      - postgres
      - mongo
    ports:
      #- '83:80'
      - '83:8080'
    restart: always
    networks:
      internal:
      shared:
        ipv4_address: 172.55.0.10

 
